name: Continuous Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy-to-minikube:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Minikube
        uses: dawidd6/action-setup-minikube@v2

      - name: Install kubectl
        uses: azure/setup-kubectl@v1.0.0

      - name: Load Docker image into Minikube
        run: |
          eval $(minikube -p minikube docker-env)
          docker pull ghcr.io/dafessor/devops-ci-demo/devops-ci-demo-img:latest
          docker tag ghcr.io/dafessor/devops-ci-demo/devops-ci-demo-img:latest minikube/devops-ci-demo-img:latest
          docker images

      - name: Apply Kubernetes Deployment
        run: kubectl apply -f kubernetes/deployment.yaml

      - name: Apply Kubernetes Service
        run: kubectl apply -f kubernetes/service.yaml
