name: CI/CD Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn clean install

      - name: Build Docker Image
        run: docker build -t ghcr.io/dafessor/devops-ci-demo/devops-ci-demo-img:latest .

      - name: Push Docker Image
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker push ghcr.io/dafessor/devops-ci-demo/devops-ci-demo-img:latest

  deploy-to-minikube:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Minikube
        run: |
          curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          sudo install minikube-linux-amd64 /usr/local/bin/minikube

      - name: Start Minikube
        run: |
          minikube start --driver=none

      - name: Set Minikube Context
        run: |
          kubectl config use-context minikube

      - name: Deploy to Minikube
        run: |
          kubectl apply -f devops-ci-demo-deployment.yaml

      - name: Update Deployment Image
        run: |
          kubectl set image deployment/devops-ci-demo devops-ci-demo=ghcr.io/dafessor/devops-ci-demo/devops-ci-demo-img:latest

      - name: Check Deployment Status
        run: |
          kubectl rollout status deployment/devops-ci-demo
