apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-doc-example
  labels:
    app: k8s-doc-example
spec:
  replicas: 2
  selector:
    matchLabels:
      app: k8s-doc-example
  template:
    metadata:
      labels:
        app: k8s-doc-example
    spec:
      containers:
        - name: k8s-doc-example
          image: k8s-doc-example:v2.15.3
          imagePullPolicy: Never
          ports:
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: k8s-doc-example
spec:
  type: NodePort
  selector:
    app: k8s-doc-example
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      # nodePort: 30852 (optional, can be uncommented if a specific port is required externally)
